### ISSUE TITLE
issue with period "." character and regex

### ISSUE THREAD

**Issue by sam0x17** [DanilaFe/pegasus#3]
This has been giving me trouble as well:

```
S = FLOAT;
FLOAT = "[0-9]*.[0-9]+";
```

```
nojs$ echo '22.2' | pegasus-sim -i test.json
ParentTree(S)
  ParentTree(FLOAT)
    Token(1, 22.2)
(correct)
nojs$ echo '22.' | pegasus-sim -i test.json
ParentTree(S)
  ParentTree(FLOAT)
    Token(1, 22)
(shouldn't work because no ".")
nojs$ echo '.2' | pegasus-sim -i test.json
ParentTree(S)
  ParentTree(FLOAT)
    Token(1, .2)
(correct)
```

It's allowing a plain "2" to be a float, even though there is no ".". I'm pretty sure it's not my regex but something else going on with how the regex is parsed.

**Comment by DanilaFe** [comment]
`.` is actually a reserved character in regular expressions that represents any character. It needs to be escaped to be used as a period character, and I just fixed the fact that it wasn't allowed to be escaped (similar to #2 )

**Comment by sam0x17** [comment]
ah ok perfect that is why thanks!
