### ISSUE TITLE
Semantic actions call in README has wrong flags.

### ISSUE THREAD

**Issue by badBlackShark** [DanilaFe/pegasus#6]
Hi :)

In the README the example for the csem generator reads `./bin/pegasus-csem -a test.json -b test.sem`. However, the options are no longer `-a` and `-b`, but `-l` and `-a`. This is of course not a big deal, and I don't wanna make a PR for such a minuscule change, but I still think this should be adjusted.

Otherwise thank you for this program! I just used it for one of my projects, and I'm very happy with it :)

Cheers,
Shark

**Comment by DanilaFe** [comment]
Hi!

Thanks so much for opening the issue. I'm glad you're liking Pegasus :)

You are right, the documentation was slightly out of date. I have updated the flags to be `-l` and `-a` in the README (1d92bf60f2b5bd7b142a57330865bb6873366cbe). I've only found one instance of this mistake.

Thanks again, and have a nice day!
Daniel

**Comment by badBlackShark** [comment]
I needed a small parser for my some work on my Bachelor thesis, and this was honestly perfect! Thanks for the quick fix, will close the issue :)
